### ISSUE TITLE
Description about max_frames_per_video in config

### ISSUE THREAD

**Issue by MrinalTyagi** [dipika-singhania/C2F-TCN#3]
Hii. While going through your code I came across the max_frames_per_video in the config and was confused about its value as the maximum frames in specific datasets are less than specified in the config. Is it possible to provide info on the same? 
Hoping for a response soon.

**Comment by dipika-singhania** [comment]
Sorry, I am unable to understand which config are you referring to.

In C2FTCN we required fixed length video processing, so we took max-frames which can be processed per video. If video is smaller than max-frames, it is padded with -100s and if video is longer than max-frames then video is split after max-frames and processed as 2(or multiple) videos. This is joined in the post-processing step.
